version: '3.5'

services:
  postgres:
    container_name: clubdb
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: senhasenha
      POSTGRES_DB: club
      PGDATA: /data/postgres
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256"
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
volumes:
  postgres:
